### ISSUE TITLE
Bug: stackit beta network list causes PANIC

### ISSUE THREAD

**Issue by MrTrustworthy** [stackitcloud/stackit-cli#511]
Context:
* I've created one network in a SNA project manually in the UI
* `stackit beta network list` and `describe <id>` work fine
* I've added a second network into the project using Terraform (snippet below) 
* The network is there, and both Terraform and the UI have no problem showing it
* However,  `stackit beta network list` and `describe <id>` now throw an error (snippet below, exact same error on both commands)

Terraform snippet:

```HCL
resource "stackit_network" "test_network_2" {
  project_id         = var.project_id
  name               = "example-non-routed-network"
  ipv4_prefix        = "172.16.2.0/24"
  labels = {
    "test" = "yes"
  }
  routed = false
}
```

Error message:
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102a4515c]

goroutine 1 [running]:
github.com/stackitcloud/stackit-cli/internal/cmd/beta/network/describe.outputResult(0x140003839e0, {0x0?, 0x140003838f8?}, 0x1400003a0a0)
	/Users/runner/work/stackit-cli/stackit-cli/internal/cmd/beta/network/describe/describe.go:149 +0x71c
github.com/stackitcloud/stackit-cli/internal/cmd/beta/network/describe.NewCmd.func1(0x14000486c08?, {0x14000350b40?, 0x1?, 0x10354d3f3?})
	/Users/runner/work/stackit-cli/stackit-cli/internal/cmd/beta/network/describe/describe.go:68 +0x148
github.com/spf13/cobra.(*Command).execute(0x14000486c08, {0x14000350b00, 0x1, 0x1})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14000140f08)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/stackitcloud/stackit-cli/internal/cmd.Execute({0x1037c9464, 0x6}, {0x1037c9800, 0x14})
	/Users/runner/work/stackit-cli/stackit-cli/internal/cmd/root.go:186 +0x98
main.main()
	/Users/runner/work/stackit-cli/stackit-cli/main.go:18 +0x40

```

**Comment by GokceGK** [comment]
Hi @MrTrustworthy, 

thanks for reporting the issue. It has been fixed in the release [v0.17.0](https://github.com/stackitcloud/stackit-cli/releases/tag/v0.17.0). 

If the problem persists, feel free to reopen the issue.
